[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    pschatzmann/ESP32-A2DP @ ^1.7.3

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
